In [129]:
import pandas as pd

In [130]:
df1 = pd.read_csv('telecom_demographics.csv')
df2 = pd.read_csv('telecom_usage.csv')

In [131]:
df1.head()

,customer_id,telecom_partner,gender,age,state,city,pincode,registration_event,num_dependents,estimated_salary
0,15169,Airtel,F,26,Himachal Pradesh,Delhi,667173,2020-03-16,4,85979
1,149207,Airtel,F,74,Uttarakhand,Hyderabad,313997,2022-01-16,0,69445
2,148119,Airtel,F,54,Jharkhand,Chennai,549925,2022-01-11,2,75949
3,187288,Reliance Jio,M,29,Bihar,Hyderabad,230636,2022-07-26,3,34272
4,14016,Vodafone,M,45,Nagaland,Bangalore,188036,2020-03-11,4,34157

In [132]:
df2.head()

   customer_id  calls_made  sms_sent  data_used  churn
0        15169          75        21       4532      1
1       149207          35        38        723      1
2       148119          70        47       4688      1
3       187288          95        32      10241      1
4        14016          66        23       5246      1

In [133]:
#Merge them together
churn_df = pd.merge(df1, df2, on='customer_id')
churn_df

,customer_id,telecom_partner,gender,age,state,city,pincode,registration_event,num_dependents,estimated_salary,calls_made,sms_sent,data_used,churn
0,15169,Airtel,F,26,Himachal Pradesh,Delhi,667173,2020-03-16,4,85979,75,21,4532,1
1,149207,Airtel,F,74,Uttarakhand,Hyderabad,313997,2022-01-16,0,69445,35,38,723,1
2,148119,Airtel,F,54,Jharkhand,Chennai,549925,2022-01-11,2,75949,70,47,4688,1
3,187288,Reliance Jio,M,29,Bihar,Hyderabad,230636,2022-07-26,3,34272,95,32,10241,1
4,14016,Vodafone,M,45,Nagaland,Bangalore,188036,2020-03-11,4,34157,66,23,5246,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6495,78836,Airtel,M,54,Odisha,Chennai,125785,2021-01-29,4,124805,-2,39,5000,0
6496,146521,BSNL,M,69,Andhra Pradesh,Hyderabad,923076,2022-01-03,1,65605,20,31,3562,0
6497,40413,Airtel,M,19,Gujarat,Hyderabad,152201,2020-07-21,0,28632,73,14,65,0
6498,64961,Vodafone,M,26,Meghalaya,Chennai,782127,2020-11-21,3,119757,52,8,6835,0
6499,60427,Reliance Jio,M,19,Mizoram,Hyderabad,918496,2020-10-29,3,119368,90,12,5531,0

In [134]:
churn_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6500 entries, 0 to 6499
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer_id         6500 non-null   int64
 1   telecom_partner     6500 non-null   object
 2   gender              6500 non-null   object
 3   age                 6500 non-null   int64
 4   state               6500 non-null   object
 5   city                6500 non-null   object
 6   pincode             6500 non-null   int64
 7   registration_event  6500 non-null   object
 8   num_dependents      6500 non-null   int64
 9   estimated_salary    6500 non-null   int64
 10  calls_made          6500 non-null   int64
 11  sms_sent            6500 non-null   int64
 12  data_used           6500 non-null   int64
 13  churn               6500 non-null   int64
dtypes: int64(9), object(5)
memory usage: 711.1+ KB

In [135]:
# prompt: #apply one hot encoding to telecom_partner

#Get one hot encoding of columns 'telecom_partner'
one_hot = pd.get_dummies(churn_df['telecom_partner'])
#Drop column B as it is now encoded
churn_df = churn_df.drop('telecom_partner',axis = 1)
#Join the encoded df
churn_df = churn_df.join(one_hot)
churn_df

,customer_id,gender,age,state,city,pincode,registration_event,num_dependents,estimated_salary,calls_made,sms_sent,data_used,churn,Airtel,BSNL,Reliance Jio,Vodafone
0,15169,F,26,Himachal Pradesh,Delhi,667173,2020-03-16,4,85979,75,21,4532,1,True,False,False,False
1,149207,F,74,Uttarakhand,Hyderabad,313997,2022-01-16,0,69445,35,38,723,1,True,False,False,False
2,148119,F,54,Jharkhand,Chennai,549925,2022-01-11,2,75949,70,47,4688,1,True,False,False,False
3,187288,M,29,Bihar,Hyderabad,230636,2022-07-26,3,34272,95,32,10241,1,False,False,True,False
4,14016,M,45,Nagaland,Bangalore,188036,2020-03-11,4,34157,66,23,5246,1,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6495,78836,M,54,Odisha,Chennai,125785,2021-01-29,4,124805,-2,39,5000,0,True,False,False,False
6496,146521,M,69,Andhra Pradesh,Hyderabad,923076,2022-01-03,1,65605,20,31,3562,0,False,True,False,False
6497,40413,M,19,Gujarat,Hyderabad,152201,2020-07-21,0,28632,73,14,65,0,True,False,False,False
6498,64961,M,26,Meghalaya,Chennai,782127,2020-11-21,3,119757,52,8,6835,0,False,False,False,True
6499,60427,M,19,Mizoram,Hyderabad,918496,2020-10-29,3,119368,90,12,5531,0,False,False,True,False

In [136]:
# prompt: Apply one hot encoding to city making sure the values of the new columns are numerical in 1s and 0s instead of true and false

#Get one hot encoding of columns 'city'
one_hot = pd.get_dummies(churn_df['city'])
#Drop column B as it is now encoded
churn_df = churn_df.drop('city',axis = 1)
#Join the encoded df
churn_df = churn_df.join(one_hot)

# Convert boolean values to numerical (1 and 0)
churn_df = churn_df.replace({True: 1, False: 0})
churn_df

,customer_id,gender,age,state,pincode,registration_event,num_dependents,estimated_salary,calls_made,sms_sent,...,Airtel,BSNL,Reliance Jio,Vodafone,Bangalore,Chennai,Delhi,Hyderabad,Kolkata,Mumbai
0,15169,F,26,Himachal Pradesh,667173,2020-03-16,4,85979,75,21,...,1,0,0,0,0,0,1,0,0,0
1,149207,F,74,Uttarakhand,313997,2022-01-16,0,69445,35,38,...,1,0,0,0,0,0,0,1,0,0
2,148119,F,54,Jharkhand,549925,2022-01-11,2,75949,70,47,...,1,0,0,0,0,1,0,0,0,0
3,187288,M,29,Bihar,230636,2022-07-26,3,34272,95,32,...,0,0,1,0,0,0,0,1,0,0
4,14016,M,45,Nagaland,188036,2020-03-11,4,34157,66,23,...,0,0,0,1,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6495,78836,M,54,Odisha,125785,2021-01-29,4,124805,-2,39,...,1,0,0,0,0,1,0,0,0,0
6496,146521,M,69,Andhra Pradesh,923076,2022-01-03,1,65605,20,31,...,0,1,0,0,0,0,0,1,0,0
6497,40413,M,19,Gujarat,152201,2020-07-21,0,28632,73,14,...,1,0,0,0,0,0,0,1,0,0
6498,64961,M,26,Meghalaya,782127,2020-11-21,3,119757,52,8,...,0,0,0,1,0,1,0,0,0,0
6499,60427,M,19,Mizoram,918496,2020-10-29,3,119368,90,12,...,0,0,1,0,0,0,0,1,0,0

In [137]:
# prompt: Convert registration_event to date time datatype one of its value is 2020-02-02

churn_df['registration_event'] = pd.to_datetime(churn_df['registration_event'], format='%Y-%m-%d')

In [138]:
# prompt: SEPERATE registration event to year month and day

churn_df['registration_year'] = churn_df['registration_event'].dt.year
churn_df['registration_month'] = churn_df['registration_event'].dt.month
churn_df['registration_day'] = churn_df['registration_event'].dt.day

In [139]:
churn_df.drop('registration_event', axis=1, inplace=True)

In [140]:
df = churn_df.copy()
df

,customer_id,gender,age,state,pincode,num_dependents,estimated_salary,calls_made,sms_sent,data_used,...,Vodafone,Bangalore,Chennai,Delhi,Hyderabad,Kolkata,Mumbai,registration_year,registration_month,registration_day
0,15169,F,26,Himachal Pradesh,667173,4,85979,75,21,4532,...,0,0,0,1,0,0,0,2020,3,16
1,149207,F,74,Uttarakhand,313997,0,69445,35,38,723,...,0,0,0,0,1,0,0,2022,1,16
2,148119,F,54,Jharkhand,549925,2,75949,70,47,4688,...,0,0,1,0,0,0,0,2022,1,11
3,187288,M,29,Bihar,230636,3,34272,95,32,10241,...,0,0,0,0,1,0,0,2022,7,26
4,14016,M,45,Nagaland,188036,4,34157,66,23,5246,...,1,1,0,0,0,0,0,2020,3,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6495,78836,M,54,Odisha,125785,4,124805,-2,39,5000,...,0,0,1,0,0,0,0,2021,1,29
6496,146521,M,69,Andhra Pradesh,923076,1,65605,20,31,3562,...,0,0,0,0,1,0,0,2022,1,3
6497,40413,M,19,Gujarat,152201,0,28632,73,14,65,...,0,0,0,0,1,0,0,2020,7,21
6498,64961,M,26,Meghalaya,782127,3,119757,52,8,6835,...,1,0,1,0,0,0,0,2020,11,21
6499,60427,M,19,Mizoram,918496,3,119368,90,12,5531,...,0,0,0,0,1,0,0,2020,10,29

In [141]:
df.drop('customer_id', axis=1, inplace=True)

In [142]:
# prompt: Label encode gender column

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['gender'] = le.fit_transform(df['gender'])

In [143]:
from category_encoders import TargetEncoder

# Initialize TargetEncoder
encoder = TargetEncoder()

# Fit and transform the 'state' column
df['state'] = encoder.fit_transform(df['state'], df['churn'])

In [144]:
df

,gender,age,state,pincode,num_dependents,estimated_salary,calls_made,sms_sent,data_used,churn,...,Vodafone,Bangalore,Chennai,Delhi,Hyderabad,Kolkata,Mumbai,registration_year,registration_month,registration_day
0,0,26,0.215517,667173,4,85979,75,21,4532,1,...,0,0,0,1,0,0,0,2020,3,16
1,0,74,0.220264,313997,0,69445,35,38,723,1,...,0,0,0,0,1,0,0,2022,1,16
2,0,54,0.203125,549925,2,75949,70,47,4688,1,...,0,0,1,0,0,0,0,2022,1,11
3,1,29,0.184332,230636,3,34272,95,32,10241,1,...,0,0,0,0,1,0,0,2022,7,26
4,1,45,0.177215,188036,4,34157,66,23,5246,1,...,1,1,0,0,0,0,0,2020,3,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6495,1,54,0.198312,125785,4,124805,-2,39,5000,0,...,0,0,1,0,0,0,0,2021,1,29
6496,1,69,0.213333,923076,1,65605,20,31,3562,0,...,0,0,0,0,1,0,0,2022,1,3
6497,1,19,0.200893,152201,0,28632,73,14,65,0,...,0,0,0,0,1,0,0,2020,7,21
6498,1,26,0.214286,782127,3,119757,52,8,6835,0,...,1,0,1,0,0,0,0,2020,11,21
6499,1,19,0.262097,918496,3,119368,90,12,5531,0,...,0,0,0,0,1,0,0,2020,10,29

In [145]:
# prompt: place churn column at the last

# Get a list of columns
cols = list(df.columns)

# Move the 'churn' column to the last position
cols.append(cols.pop(cols.index('churn')))

# Reorder the DataFrame columns
df = df[cols]
df

,gender,age,state,pincode,num_dependents,estimated_salary,calls_made,sms_sent,data_used,Airtel,...,Bangalore,Chennai,Delhi,Hyderabad,Kolkata,Mumbai,registration_year,registration_month,registration_day,churn
0,0,26,0.215517,667173,4,85979,75,21,4532,1,...,0,0,1,0,0,0,2020,3,16,1
1,0,74,0.220264,313997,0,69445,35,38,723,1,...,0,0,0,1,0,0,2022,1,16,1
2,0,54,0.203125,549925,2,75949,70,47,4688,1,...,0,1,0,0,0,0,2022,1,11,1
3,1,29,0.184332,230636,3,34272,95,32,10241,0,...,0,0,0,1,0,0,2022,7,26,1
4,1,45,0.177215,188036,4,34157,66,23,5246,0,...,1,0,0,0,0,0,2020,3,11,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6495,1,54,0.198312,125785,4,124805,-2,39,5000,1,...,0,1,0,0,0,0,2021,1,29,0
6496,1,69,0.213333,923076,1,65605,20,31,3562,0,...,0,0,0,1,0,0,2022,1,3,0
6497,1,19,0.200893,152201,0,28632,73,14,65,1,...,0,0,0,1,0,0,2020,7,21,0
6498,1,26,0.214286,782127,3,119757,52,8,6835,0,...,0,1,0,0,0,0,2020,11,21,0
6499,1,19,0.262097,918496,3,119368,90,12,5531,0,...,0,0,0,1,0,0,2020,10,29,0

In [146]:
df.info( )

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6500 entries, 0 to 6499
Data columns (total 23 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   gender              6500 non-null   int64
 1   age                 6500 non-null   int64
 2   state               6500 non-null   float64
 3   pincode             6500 non-null   int64
 4   num_dependents      6500 non-null   int64
 5   estimated_salary    6500 non-null   int64
 6   calls_made          6500 non-null   int64
 7   sms_sent            6500 non-null   int64
 8   data_used           6500 non-null   int64
 9   Airtel              6500 non-null   int64
 10  BSNL                6500 non-null   int64
 11  Reliance Jio        6500 non-null   int64
 12  Vodafone            6500 non-null   int64
 13  Bangalore           6500 non-null   int64
 14  Chennai             6500 non-null   int64
 15  Delhi               6500 non-null   int64
 16  Hyderabad           6500 non-null   int64
 17  Kolkata             6500 non-null   int64
 18  Mumbai              6500 non-null   int64
 19  registration_year   6500 non-null   int32
 20  registration_month  6500 non-null   int32
 21  registration_day    6500 non-null   int32
 22  churn               6500 non-null   int64
dtypes: float64(1), int32(3), int64(19)
memory usage: 1.1 MB

In [147]:
# prompt: Apply train test split

from sklearn.model_selection import train_test_split

X = df.drop('churn', axis=1)
y = df['churn']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [148]:
# prompt: Apply min max scaler to x and y trains

from sklearn.preprocessing import MinMaxScaler
# Initialize the scaler
scaler = MinMaxScaler()

# Fit and transform the training data
X_train = scaler.fit_transform(X_train)

# Transform the testing data using the same scaler
X_test = scaler.transform(X_test)

In [149]:
# prompt: apply logistic regression

from sklearn.linear_model import LogisticRegression

# Initialize LogisticRegression model
logreg = LogisticRegression()

# Fit the model to the scaled training data
logreg.fit(X_train, y_train)

#classification report

from sklearn.metrics import classification_report

# Make predictions on the scaled test data
y_pred = logreg.predict(X_test)

# Print the classification report
print(classification_report(y_test, y_pred))

#Accuracy

from sklearn.metrics import accuracy_score

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)

# Print the accuracy
print("Accuracy:", accuracy)

              precision    recall  f1-score   support

           0       0.79      1.00      0.88      1027
           1       0.00      0.00      0.00       273

    accuracy                           0.79      1300
   macro avg       0.40      0.50      0.44      1300
weighted avg       0.62      0.79      0.70      1300

Accuracy: 0.79

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [150]:
# prompt: Apply random forest

from sklearn.ensemble import RandomForestClassifier

# Initialize RandomForestClassifier model
rf = RandomForestClassifier()

# Fit the model to the scaled training data
rf.fit(X_train, y_train)

# Make predictions on the scaled test data
y_pred_rf = rf.predict(X_test)

# Print the classification report
print("Random Forest Classification Report:")
print(classification_report(y_test, y_pred_rf))

# Calculate accuracy
accuracy_rf = accuracy_score(y_test, y_pred_rf)

# Print the accuracy
print("Random Forest Accuracy:", accuracy_rf)

Random Forest Classification Report:
              precision    recall  f1-score   support

           0       0.79      1.00      0.88      1027
           1       0.00      0.00      0.00       273

    accuracy                           0.79      1300
   macro avg       0.40      0.50      0.44      1300
weighted avg       0.62      0.79      0.70      1300

Random Forest Accuracy: 0.79

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))