In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('bank.csv')
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,59,admin.,married,secondary,no,2343,yes,no,unknown,5,may,1042,1,-1,0,unknown,yes
1,56,admin.,married,secondary,no,45,no,no,unknown,5,may,1467,1,-1,0,unknown,yes
2,41,technician,married,secondary,no,1270,yes,no,unknown,5,may,1389,1,-1,0,unknown,yes
3,55,services,married,secondary,no,2476,yes,no,unknown,5,may,579,1,-1,0,unknown,yes
4,54,admin.,married,tertiary,no,184,no,no,unknown,5,may,673,2,-1,0,unknown,yes

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11162 entries, 0 to 11161
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        11162 non-null  int64
 1   job        11162 non-null  object
 2   marital    11162 non-null  object
 3   education  11162 non-null  object
 4   default    11162 non-null  object
 5   balance    11162 non-null  int64
 6   housing    11162 non-null  object
 7   loan       11162 non-null  object
 8   contact    11162 non-null  object
 9   day        11162 non-null  int64
 10  month      11162 non-null  object
 11  duration   11162 non-null  int64
 12  campaign   11162 non-null  int64
 13  pdays      11162 non-null  int64
 14  previous   11162 non-null  int64
 15  poutcome   11162 non-null  object
 16  deposit    11162 non-null  object
dtypes: int64(7), object(10)
memory usage: 1.4+ MB

In [5]:
df.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
deposit      0
dtype: int64

In [7]:
df_demographic = df[['age', 'job', 'marital', 'education']]
df_financial = df[['balance', 'default', 'housing', 'loan']]
df_campaign = df[['contact', 'day', 'month', 'duration', 'campaign', 'pdays', 'previous', 'poutcome', 'deposit']]

In [8]:
df_demographic

       age          job  marital  education
0       59       admin.  married  secondary
1       56       admin.  married  secondary
2       41   technician  married  secondary
3       55     services  married  secondary
4       54       admin.  married   tertiary
...    ...          ...      ...        ...
11157   33  blue-collar   single    primary
11158   39     services  married  secondary
11159   32   technician   single  secondary
11160   43   technician  married  secondary
11161   34   technician  married  secondary

[11162 rows x 4 columns]

In [9]:
#Save the three dataframes into seperate csv's
df_demographic.to_csv('demographic.csv', index=False)
df_financial.to_csv('financial.csv', index=False)
df_campaign.to_csv('campaign.csv', index=False)

SyntaxError: invalid syntax (<ipython-input-9-4b37ef281455>, line 1)